version: '3'
services:

    mysql:
        image: mysql:8
        container_name: mysql
        restart: unless-stopped
        ports:
            - "${MYSQL_PORT}:3306"
        volumes:
            - ./mysql/data:/var/lib/mysql
        environment:
            - MYSQL_HOST=${MYSQL_HOST}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        env_file:
            - ./.env
        networks:
            - code-network
        
    nginx:
        build: ./nginx
        container_name: nginx
        restart: unless-stopped
        volumes:
            - ${APPLICATIONS}:/var/www/html:rw
            - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/data/sites:/etc/nginx/sites-enabled
            - ./nginx/data/logs:/var/log/nginx
        ports:
            - "${NGINX_HOST_HTTP_PORT}:80"
            - "${NGINX_HOST_HTTPS_PORT}:443"
        env_file:
            - ./.env
        links:
            - mysql
        depends_on:
            - mysql
        networks:
            - code-network

networks:
    code-network:
        driver: bridge